class Models:
    country = 'res.country'
    user = 'res.users'
    partner = 'res.partner'
    state = 'res.country.state'
    city = 'res.city'
    company = 'res.company'
    site = 'syn.site'
    vendor = 'syn.vendor'
    grn = 'syn.grn'
    grn_line = 'syn.grn.line'
    purchase_order = 'syn.purchase.order'
    purchase_order_line = 'syn.purchase.order.line'
    material_requisition = 'syn.material.requisition'
    material_requisition_line = 'syn.material.requisition.line'
    groups = 'res.groups'
    model_access = 'ir.model.access'

